### ISSUE TITLE
Key Error in CharClassifier while loading own image with Bounding Box

### ISSUE THREAD

**Issue by yupmanojhere** [Breta01/handwriting-ocr#54]
![capture](https://user-images.githubusercontent.com/42448389/44225861-2717dc00-a154-11e8-9084-b765e39913ef.PNG)

I attached my Issue,
I'm Trying to Train the CharClassifier model with my own image dataset, where i converted the image with txt file of bounding box.
But still it throws me key error of '1' and '.'.

please do the needfull

**Comment by Breta01** [comment]
Sorry for delayed answer. The issue is quite simple, go to the [`ocr/datahelpers.py`](https://github.com/Breta01/handwriting-ocr/blob/master/ocr/datahelpers.py) there are in variable `CHARS` specified all characters which the model can use. There are also some special characters with accents, so remove them first and than add your own characters, for example:
```Python
CHARS = ['', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
         'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
         'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c',
         'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
         'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w',
         'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6',
         '7', '8', '9', '.', ',']
```
Then you will also have to change number of characters `char_size` in your code.

**Comment by yupmanojhere** [comment]
Thanks Bret,
It solved my error.
I got Another Question,
I have been training CharClassifier of CNN model,
I came across Train_steps,Test_iteration,save_iteration, and Batch Size
while I'm giving giving default value for training for 200 word images,and train_steps of 1000 it gives accuracy of 80.
But i need Accuracy above 95,in which OCR have to predict correct output.
may i know the Correct way for that.
